version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "davidlienhard"
    reviewers:
      - "davidlienhard"
    labels:
      - "enhancement"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "davidlienhard"
    reviewers:
      - "davidlienhard"
    labels:
      - "enhancement"
      - "dependencies"
